services:
  backend:

    build:
      context: ..
      dockerfile: Dockerfile


    image: backend-test:local

    container_name: backend-dev
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
