name: rollback

on:
  # 수동 실행 이벤트 트리거
  workflow_dispatch:
    inputs:
      input_sha:
        description: "배포할 SHA값을 입력"
        required: true
        default: "dev"

env:
  IMAGE: ghcr.io/b1ackc/cicd-backend-test
  NAME: backend-dev
  HOST_PORT: 8080
  CONTAINER_PORT: 8080

  # 중복실행 방지
concurrency:
  group: rollback ${{ github.ref }}
  cancel-in-progress: false

jobs:
  rollback:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - name: rollback deploy
        uses: appleboy/ssh-action@v1.2.0
        env:
          IMAGE: ${{ env.IMAGE }}
          TAG: ${{ inputs.input_sha }}
          NAME: ${{ env.NAME }}
          HOST_PORT: ${{ env.HOST_PORT }}
          CONTAINER_PORT: ${{ env.CONTAINER_PORT }}
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PASSWORD }}
          envs: IMAGE, TAG, NAME, HOST_PORT, CONTAINER_PORT
          script: |
            set -euo pipefail
    
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            TARGET_IMG="${IMAGE}:dev-${TAG}"
            docker pull "$TARGET_IMG"
            docker rm -f "${NAME}" 2>/dev/null || true
    
            docker run -d --name "${NAME}" \
              -p "${HOST_PORT}:${CONTAINER_PORT}" \
              --restart unless-stopped \
              "$TARGET_IMG"
    
            docker image prune -f
          
