name: rollback

on:
  # 수동 실행 이벤트 트리거
  workflow_dispatch:
    inputs:
      input_sha:
        description: "배포할 SHA값을 입력"
        required: true

env:
  IMAGE: ghcr.io/b1ackc/cicd-backend-test
  NAME: backend-dev
  HOST_PORT: 8081
  CONTAINER_PORT: 8081

  # 중복실행 방지
concurrency:
  group: rollback ${{ github.ref }}
  cancel-in-progress: false

jobs:
  rollback:
    runs-on: cicd-test
    permissions:
        contents: read
        packages: read

    env:
      TAG: ${{ github.event.inputs.input_sha }}

    steps:
      - name: login ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: rollback
        run: |
          set -euo pipefail
    
          TARGET_IMG="${IMAGE}:dev-${TAG}"
          docker pull "$TARGET_IMG"
          docker rm -f "${NAME}" 2>/dev/null || true
    
          docker run -d --name "${NAME}" \
            -p "${HOST_PORT}:${CONTAINER_PORT}" \
            --restart unless-stopped \
            "$TARGET_IMG"
    
          docker image prune -f
          
